services:
  backend:
    build:
      context: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx-webserver
    ports:
      - "8080:80"
    depends_on:
      - backend  # Ensure backend starts before nginx
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
