version: "3.9"

services:
  backend:
    image: us-central1-docker.pkg.dev/inspired-alcove-470811-f5/my-repo/backend:latest
    container_name: flask-app_backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: us-central1-docker.pkg.dev/inspired-alcove-470811-f5/my-repo/flask-app-nginx:latest
    container_name: flask-app_nginx
    ports:
      - "80:80"
    depends_on: 
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
